### ISSUE TITLE
Linux arm64 build

### ISSUE THREAD

**Issue by nenadalm** [stuntrally/stuntrally3#42]
Hi.It looks like SR works on arm64 https://github.com/stuntrally/stuntrally3/issues/29 but when I downloaded  linux version from releases https://github.com/stuntrally/stuntrally3/releases/ and tried to run it, it complained about wrong binary format. I assume it was because binary wasn't for arm64. It would be nice to have such binary in releases, so I could easily run SR on raspberry pi 5.

**Comment by cryham** [comment]
Quoting from #29: https://github.com/stuntrally/stuntrally3/issues/29#issuecomment-2227033448
"Stuntrally 2.7 on my RPi5 - this worked actually pretty well (after collecting all the dependencies) and the performance is pretty good - mostly 20-40 fps"
SR 2.7 is older: https://github.com/stuntrally/stuntrally
not maintained.
This is **SR 3**.3 and in here:
https://github.com/stuntrally/stuntrally3/issues/29#issuecomment-2224061058
you'll see that it's **not** possible. GL ES is quite reduced, and I surely don't have a way to test.
SR3 aims at mid and high end GPUs, not Pi5 or such low power devices. If it works there fine, but it's not official.
So, unless somebody confirms it works on arm64, posts some guide, because I didn't yet do such build myself, and it also needs more effort doing a release. So won't do.
